.PHONY: help up down logs build test lint fmt smoke migrate shell

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

up: ## Build + start the full stack
	docker compose up -d --build

down: ## Stop the stack and wipe volumes
	docker compose down -v

logs: ## Tail api + worker logs
	docker compose logs -f api worker

build: ## Build the image
	docker compose build

test: ## Run the unit + integration test suite with coverage
	pytest

itest: ## Run the pytest-docker suite (real Postgres + Redis)
	pytest integration_tests/ -o addopts="-ra"

lint: ## Run flake8
	flake8 app tests scripts integration_tests

smoke: ## End-to-end check against a running stack
	./scripts/smoke.sh

openapi: ## Regenerate the committed OpenAPI spec from the code
	python scripts/export_openapi.py

contract: ## Run Schemathesis against a running stack (needs: make up)
	schemathesis --config-file schemathesis.toml run http://localhost:8000/openapi.json

postman: ## Run the Newman smoke suite against a running stack
	npx newman@6.2.1 run postman/smoke.postman_collection.json -e postman/local.postman_environment.json --working-dir postman

loadtest: ## Run the k6 load test against a running stack (enforces the SLO)
	./loadtest/run.sh

migrate: ## Create a new autogenerated migration (msg="...")
	alembic revision --autogenerate -m "$(msg)"

shell: ## psql shell into the compose Postgres
	docker compose exec postgres psql -U snaptrack
