.PHONY: help up down logs build test lint fmt smoke migrate shell

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

up: ## Build + start the full stack
	docker compose up -d --build

down: ## Stop the stack and wipe volumes
	docker compose down -v

logs: ## Tail api + worker logs
	docker compose logs -f api worker

build: ## Build the image
	docker compose build

test: ## Run the test suite with coverage
	pytest

lint: ## Run flake8
	flake8 app tests

smoke: ## End-to-end check against a running stack
	./scripts/smoke.sh

migrate: ## Create a new autogenerated migration (msg="...")
	alembic revision --autogenerate -m "$(msg)"

shell: ## psql shell into the compose Postgres
	docker compose exec postgres psql -U snaptrack
